### ISSUE TITLE
CT50 V1.92 Support

### ISSUE THREAD

**Issue by mmbridges** [mhrivnak/radiotherm#13]
Thanks for developing this wonderful package. It is exactly what I have been looking to use on my RPi2 x-mas gift. I have two CT50 V1.92 themostats in the house and I have installed radiotherm v1.2 on my Rpi2. Do you have any suggestions of what I'm doing wrong or does the code need to be modified to support my stats?

Below is the result of my installation and 1st attempt to read temperature. Hopefully it will be useful:
## The following was at the command shell prompt:

pi@raspberrypi:~ $ sudo pip-3.2 install radiotherm
Downloading/unpacking radiotherm
Downloading radiotherm-1.2.tar.gz
Running setup.py (path:/tmp/pip-build-z5qyz6ne/radiotherm/setup.py) egg_info for package radiotherm

Installing collected packages: radiotherm
Running setup.py install for radiotherm

Successfully installed radiotherm
Cleaning up...
## The following is at the python prompt:

> > > tstat = radiotherm.get_thermostat('192.168.1.4')
> > > tstat.temp
> > > Traceback (most recent call last):
> > >   File "<pyshell#9>", line 1, in <module>
> > >     tstat.temp
> > > AttributeError: 'NoneType' object has no attribute 'temp'
> > > tstat.tmode
> > > Traceback (most recent call last):
> > >   File "<pyshell#10>", line 1, in <module>
> > >     tstat.tmode
> > > AttributeError: 'NoneType' object has no attribute 'tmode'

**Comment by mmbridges** [comment]
By the way I know the IP addresses are correct because I have the Windows app running on my PC and it tells me details about each of my thermostats including the associated IP address.

**Comment by mmbridges** [comment]
Nevermind, I figured it out by using the most recent model update commit as a template. Stiil need to figure out how to unit test.
